version: '3.1'
services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    env_file:
      - .env
    restart: always
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.prod.sql:/docker-entrypoint-initdb.d/init.prod.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
