GET http://localhost:5000/api/items

###
POST http://localhost:5000/api/items
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
    "name": "easdddasasdsa",
    "price": "2"
}

###
PUT http://localhost:5000/api/items/2
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
    "name": "e",
    "price": "2.50"
}

###
DELETE http://localhost:5000/api/items/2
Content-Type: application/json
Authorization: BEARER {{authToken}}

###
POST {{server}}/api/users/signup
Content-Type: application/json

{
  "name": "Allan Smith",
  "email": "allan@smith.com",
  "password": "allan12345"
}

###
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "allan@smith.com",
  "password": "allan12345"
}

###
@authToken = {{login.response.body.token}}

@server = http://localhost:5000